
package fr.mickaelbaron.jaxwstutorialexercice2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NoteBookService", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr/", wsdlLocation = "http://localhost:9991/ws/notebookservice?wsdl")
public class NoteBookService_Service
    extends Service
{

    private final static URL NOTEBOOKSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTEBOOKSERVICE_EXCEPTION;
    private final static QName NOTEBOOKSERVICE_QNAME = new QName("http://jaxwstutorialexercice1.mickaelbaron.fr/", "NoteBookService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9991/ws/notebookservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTEBOOKSERVICE_WSDL_LOCATION = url;
        NOTEBOOKSERVICE_EXCEPTION = e;
    }

    public NoteBookService_Service() {
        super(__getWsdlLocation(), NOTEBOOKSERVICE_QNAME);
    }

    public NoteBookService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTEBOOKSERVICE_QNAME, features);
    }

    public NoteBookService_Service(URL wsdlLocation) {
        super(wsdlLocation, NOTEBOOKSERVICE_QNAME);
    }

    public NoteBookService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTEBOOKSERVICE_QNAME, features);
    }

    public NoteBookService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoteBookService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NoteBookService
     */
    @WebEndpoint(name = "NoteBookPort")
    public NoteBookService getNoteBookPort() {
        return super.getPort(new QName("http://jaxwstutorialexercice1.mickaelbaron.fr/", "NoteBookPort"), NoteBookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoteBookService
     */
    @WebEndpoint(name = "NoteBookPort")
    public NoteBookService getNoteBookPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxwstutorialexercice1.mickaelbaron.fr/", "NoteBookPort"), NoteBookService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTEBOOKSERVICE_EXCEPTION!= null) {
            throw NOTEBOOKSERVICE_EXCEPTION;
        }
        return NOTEBOOKSERVICE_WSDL_LOCATION;
    }

}
