
package fr.mickaelbaron.jaxwstutorialexercice2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NoteBookService", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NoteBookService {


    /**
     * 
     * @param arg0
     * @return
     *     returns fr.mickaelbaron.jaxwstutorialexercice2.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonAt", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr", className = "fr.mickaelbaron.jaxwstutorialexercice2.GetPersonAt")
    @ResponseWrapper(localName = "getPersonAtResponse", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr", className = "fr.mickaelbaron.jaxwstutorialexercice2.GetPersonAtResponse")
    @Action(input = "http://jaxwstutorialexercice1.mickaelbaron.fr/NoteBookService/getPersonAtRequest", output = "http://jaxwstutorialexercice1.mickaelbaron.fr/NoteBookService/getPersonAtResponse")
    public Person getPersonAt(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr", className = "fr.mickaelbaron.jaxwstutorialexercice2.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr", className = "fr.mickaelbaron.jaxwstutorialexercice2.AddPersonResponse")
    @Action(input = "http://jaxwstutorialexercice1.mickaelbaron.fr/NoteBookService/addPersonRequest", output = "http://jaxwstutorialexercice1.mickaelbaron.fr/NoteBookService/addPersonResponse")
    public boolean addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<fr.mickaelbaron.jaxwstutorialexercice2.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr", className = "fr.mickaelbaron.jaxwstutorialexercice2.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://jaxwstutorialexercice1.mickaelbaron.fr", className = "fr.mickaelbaron.jaxwstutorialexercice2.GetPersonsResponse")
    @Action(input = "http://jaxwstutorialexercice1.mickaelbaron.fr/NoteBookService/getPersonsRequest", output = "http://jaxwstutorialexercice1.mickaelbaron.fr/NoteBookService/getPersonsResponse")
    public List<Person> getPersons();

}
